[tool.poetry]
name = "flaskr"
version = "0.1.0"
description = ""
authors = ["jhon smith <tomi@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"
jinja2 = "^3.1.4"
mysql-connector-python = "^9.1.0"
python-dotenv = "^1.0.1"
gunicorn = "^23.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
